name: bridging
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_secure_storage: ^9.0.0
  validators: ^3.0.0
  camera: ^0.11.2
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  google_mlkit_text_recognition: 0.11.0
  google_mlkit_commons: ^0.6.1
  google_mlkit_pose_detection: ^0.10.0
  google_mlkit_face_detection: ^0.9.0
  flutter_mediapipe: ^0.0.7
  video_player: ^2.8.2
  chewie: ^1.7.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/logo.jpg
    - assets/pattern.png
    - assets/splash.png
    - assets/hand_landmarker.task
    - assets/videos/
